/* AIOS Issues Data — generated by tools/import-issues.py */
/* Source: intelligence-inbox/daily-issues/               */
/* DO NOT EDIT MANUALLY — re-run tools/import-issues.py   */
window.AIOS_ISSUES_DATA = [
  {
    id:            "ISSUE-023",
    date:          "2026-07-12",
    domain:        "purchase",
    priority:      "",
    status:        "investigation",
    title:         "Issue 023 \u2013 Vendor Box Inventory Discrepancy and Reported Calculation Method Concern (UNIT 3 / UNIT 4)",
    what:          "Operational staff reportedly calculate the number of vendor boxes required for vendor\nshipments based on unit count. The supplied BI report states:",
    gapLabel:      "\u2014",
    gapClass:      "gap-none",
    fix:           "The following are recommendations based on the supplied BI report. They are not approved\noperational procedures. Each requires business and/or management validation before action.",
    owner:         "Warehouse Operations Team",
    priorityBadge: "<span class=\"badge badge-tbd\">TBD</span>",
    evidenceHtml:  "<div class=\"evidence-gallery\"><a href=\"Phase2-inputs/issues%2023/2026_07_12_p1.png\" target=\"_blank\" class=\"evidence-link\"><img src=\"Phase2-inputs/issues%2023/2026_07_12_p1.png\" class=\"evidence-thumb\" alt=\"evidence image\" loading=\"lazy\"></a></div>",
  }
];
